### ISSUE TITLE
[ENHANCE] 中英文排版建议

### ISSUE THREAD

**Issue by wfly1998** [PKUFlyingPig/cs-self-learning#114]
非常感谢 PKUFlyingPig 为我们提供了这样一个平台，文档中提供的课程质量都非常高，课程也都很硬核，但是我想在文档的细节方面提出一些小建议：

1. 专有名词问题。我注意到文档中有部分专有名词的拼写有些错误，如 `Github` 应为 `GitHub`，`Latex` 应为 `LaTeX`；此外还有部分专有名词如 `Makefile`，我理解这里应该是 `Make` 或者 `GNU make`
2. 混合排版问题。中英文混合排版时，中文与英文字母会压在一起，所以文档中的中英文间加一个空格会显得美观一些
3. 括号全角/半角问题。括号内部是英文的话建议用半角括号，并在括号外没有标点的地方空一格，这样会显得更美观；括号内部是中文或者中英文混合的话用全角括号不空格会更美观

由于时间有限，我暂时只发现了这一些文档细节上的问题。如果不介意的话，后续我可以提交一版 Pull Request 来优化这些问题。

另外，我觉得一些国内高校的课程以及实验的质量也是比较高的，我比较了解的比如贵系的操作系统课，在[学堂在线](https://www.xuetangx.com/)可以找到，其实验也可以在 GitHub 找到，C with x86 的内核 [uCore](https://github.com/chyyuu/os_kernel_lab/tree/master) 参考了 MIT xv6 的设计，目前已经基本不用了，现在的是 Rust with RISC-V 的内核 [rCore-Tutorial-v3](https://github.com/rcore-os/rCore-Tutorial-v3) 的内核，其完整版是 [rCore](https://github.com/rcore-os/rCore)，曾经参考了 [phil-opp/blog_os](https://github.com/phil-opp/blog_os)，现在也发展得比较完善了，质量还是不错的。

此外，虽然我是忠实的 Vim 用户，但我认为 Emacs 也很值得推荐 (x)，以上部分我后续也可以提供一版 Pull Request，工作日还是得先打工的 (

**Comment by PKUFlyingPig** [comment]
非常感谢您的建议，由于最初没想到会有这样的关注度，因此文档编写得相对随意（80%的内容是两个通宵冲出来的），后续有时间会对细节进行完善和修改，当然也非常欢迎提交PR来优化这些问题。
清华的rCore我也慕名许久，一定会在不久的将来加入进本书的，预计会和南大的NEMU的project一起加进来（但最近workload太重，一直没有时间）。
Emacs也是神之编辑器之一，但本人一窍不通，欢迎大佬添加相关内容。

**Comment by wfly1998** [comment]
> 非常感谢您的建议，由于最初没想到会有这样的关注度，因此文档编写得相对随意（80%的内容是两个通宵冲出来的），后续有时间会对细节进行完善和修改，当然也非常欢迎提交PR来优化这些问题。
> 清华的rCore我也慕名许久，一定会在不久的将来加入进本书的，预计会和南大的NEMU的project一起加进来（但最近workload太重，一直没有时间）。
> Emacs也是神之编辑器之一，但本人一窍不通，欢迎大佬添加相关内容。

有这样的关注度也是可以理解的，毕竟国内高校的课程质量...而且虽然高质量的公开课很多，但一直没有一个像样的、完整的 collection，这个文档在为大家提供了学习机会的同时也节省了寻找高质量课程的时间。实不相瞒，我已经推荐给身边很多人了

关于南大的 NEMU，我认为这不算是一个很好的模拟器，毕竟其模拟功能非常有限的。但 NEMU 确实是一个可以用于处理器设计过程中非常优秀的仿真测试平台，将 NEMU 用于处理器研发过程中的差分测试可以很高效地定位问题。我印象中 NEMU 曾用于一生一芯以及计算所的 XiangShan 测试，在其中起到了非常关键的作用。现在 NJU 的 [NEMU](https://github.com/NJU-ProjectN/nemu) 也已经很久没有维护了，但香山的 [NEMU](https://github.com/OpenXiangShan/NEMU) 一直在维护。

提到这个，我觉得文档中也可以简单列一下一些国内的高质量比赛及活动，如龙芯杯全家桶（龙芯杯网站挂了，[编译系统赛](https://compiler.educg.net/)，[操作系统设计大赛](https://os.educg.net/)）和[一生一芯](https://ysyx.org/)，这可以在课程之外提供很好的实践机会。

另外，Emacs 我也不太了解，但我可以抛砖引玉 (x)

**Comment by xiaotianxt** [comment]
> 



> 非常感谢 PKUFlyingPig 为我们提供了这样一个平台，文档中提供的课程质量都非常高，课程也都很硬核，但是我想在文档的细节方面提出一些小建议：
> 
> 1. 专有名词问题。我注意到文档中有部分专有名词的拼写有些错误，如 `Github` 应为 `GitHub`，`Latex` 应为 `LaTeX`；此外还有部分专有名词如 `Makefile`，我理解这里应该是 `Make` 或者 `GNU make`
> 2. 混合排版问题。中英文混合排版时，中文与英文字母会压在一起，所以文档中的中英文间加一个空格会显得美观一些
> 3. 括号全角/半角问题。括号内部是英文的话建议用半角括号，并在括号外没有标点的地方空一格，这样会显得更美观；括号内部是中文或者中英文混合的话用全角括号不空格会更美观
> 
> 由于时间有限，我暂时只发现了这一些文档细节上的问题。如果不介意的话，后续我可以提交一版 Pull Request 来优化这些问题。
> 
> 另外，我觉得一些国内高校的课程以及实验的质量也是比较高的，我比较了解的比如贵系的操作系统课，在[学堂在线](https://www.xuetangx.com/)可以找到，其实验也可以在 GitHub 找到，C with x86 的内核 [uCore](https://github.com/chyyuu/os_kernel_lab/tree/master) 参考了 MIT xv6 的设计，目前已经基本不用了，现在的是 Rust with RISC-V 的内核 [rCore-Tutorial-v3](https://github.com/rcore-os/rCore-Tutorial-v3) 的内核，其完整版是 [rCore](https://github.com/rcore-os/rCore)，曾经参考了 [phil-opp/blog_os](https://github.com/phil-opp/blog_os)，现在也发展得比较完善了，质量还是不错的。
> 
> 此外，虽然我是忠实的 Vim 用户，但我认为 Emacs 也很值得推荐 (x)，以上部分我后续也可以提供一版 Pull Request，工作日还是得先打工的 (

关于排版的问题，我觉得[这个仓库](https://github.com/selfteaching/markdown-writing-with-mixed-cn-en)可以提供一些参考～

**Comment by PKUFlyingPig** [comment]
感谢建议，这个issue会优先被fix，我已经pin了这个issue。

**Comment by Alkaidcc** [comment]
> > 
> 
> > 非常感谢 PKUFlyingPig 为我们提供了这样一个平台，文档中提供的课程质量都非常高，课程也都很硬核，但是我想在文档的细节方面提出一些小建议：
> > 
> > 1. 专有名词问题。我注意到文档中有部分专有名词的拼写有些错误，如 `Github` 应为 `GitHub`，`Latex` 应为 `LaTeX`；此外还有部分专有名词如 `Makefile`，我理解这里应该是 `Make` 或者 `GNU make`
> > 2. 混合排版问题。中英文混合排版时，中文与英文字母会压在一起，所以文档中的中英文间加一个空格会显得美观一些
> > 3. 括号全角/半角问题。括号内部是英文的话建议用半角括号，并在括号外没有标点的地方空一格，这样会显得更美观；括号内部是中文或者中英文混合的话用全角括号不空格会更美观
> > 
> > 由于时间有限，我暂时只发现了这一些文档细节上的问题。如果不介意的话，后续我可以提交一版 Pull Request 来优化这些问题。
> > 另外，我觉得一些国内高校的课程以及实验的质量也是比较高的，我比较了解的比如贵系的操作系统课，在[学堂在线](https://www.xuetangx.com/)可以找到，其实验也可以在 GitHub 找到，C with x86 的内核 [uCore](https://github.com/chyyuu/os_kernel_lab/tree/master) 参考了 MIT xv6 的设计，目前已经基本不用了，现在的是 Rust with RISC-V 的内核 [rCore-Tutorial-v3](https://github.com/rcore-os/rCore-Tutorial-v3) 的内核，其完整版是 [rCore](https://github.com/rcore-os/rCore)，曾经参考了 [phil-opp/blog_os](https://github.com/phil-opp/blog_os)，现在也发展得比较完善了，质量还是不错的。
> > 此外，虽然我是忠实的 Vim 用户，但我认为 Emacs 也很值得推荐 (x)，以上部分我后续也可以提供一版 Pull Request，工作日还是得先打工的 (
> 
> 关于排版的问题，我觉得[这个仓库](https://github.com/selfteaching/markdown-writing-with-mixed-cn-en)可以提供一些参考～

补充一个排版指南：[中文文案排版指北](https://github.com/lhajh/chinese-copywriting-guidelines)

**Comment by PKUFlyingPig** [comment]
关于中英文排版的建议已经添加在模版中，issue 中提到的加入国内优秀课程的建议会在 #180 完成。
