### ISSUE TITLE
寻人一起学习CS61C（体系结构）, CMU15445 （数据库）

### ISSUE THREAD

**Issue by sntaoo** [PKUFlyingPig/cs-self-learning#129]
感觉自己基础薄弱，大四了没学过体系结构，也没学懂数据库，寻人一起学习，互相交流lab， proj， homework，最重要的是互相监督. 有意可加微信snt1365346940. 目前进度刚刚开始，CS61C昨天看了第一周和第二周的lecture，复习了C语言部分，正在做第一个lab

**Comment by ijpq** [comment]
cs61c已到proj3 欢迎一起

**Comment by ForeverOpp** [comment]
> cs61c已到proj3 欢迎一起

要不来个QQ群？

**Comment by sntaoo** [comment]
各位有意的可以加我vx，我会给大家拉个小群
