### ISSUE TITLE
北京大学图灵班开设的前沿计算实践网站无法代开

### ISSUE THREAD

**Issue by tgbamg** [PKUFlyingPig/cs-self-learning#137]
北京大学图灵班开设的前沿计算实践网站：http://vcl.pku.edu.cn/course/PFCII/2021-spring/index.html 无法打开，可不可以把相关课程的资料上传到这个仓库？

**Comment by PKUFlyingPig** [comment]
这个网站访问可能需要校园内网，相关资源因为版权问题我无法直接搬运。但我浏览了相关内容和 MIT Missing Semester 重合度较高，可以学习 MIT 的开源课程。
