### ISSUE TITLE
[ENHANCE] 丰富书籍推荐的内容

### ISSUE THREAD

**Issue by zll600** [PKUFlyingPig/cs-self-learning#177]
推荐书籍时，能否放上豆瓣读书的链接，

有部分书会有不同的出版社再版，放上豆瓣的链接可能会方便一点

**Comment by PKUFlyingPig** [comment]
近期在考虑改版推荐书籍的界面，仅仅提供书名感觉意义不大，希望贡献者能提供书籍内容的介绍、阅读体验等信息。

**Comment by PKUFlyingPig** [comment]
# TODO
- [ ]  改版“推荐书籍”的网站界面
- [ ] 丰富书籍推荐的内容：内容介绍、阅读体验、和其他同类书籍的区别与联系、相关配套学习资源、获取方式（开源或豆瓣链接）
- [ ] 提供推荐书籍的PR模版

**Comment by zll600** [comment]
其实我觉得书籍内容的介绍、阅读体验这些豆瓣还蛮不错的，可以考虑一下

**Comment by PKUFlyingPig** [comment]
好的，我关注一下

**Comment by imkaihao** [comment]
C/C++书籍建议直接指向stackoverflow：
https://stackoverflow.com/questions/562303/the-definitive-c-book-guide-and-list
https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list

关于Python的书，个人认为https://pythonbooks.org/ 里面分类和简介挺不错的。

此外，关于Computer Science的各个主题的教材，4chan Science Wiki里面挺全面的：https://4chan-science.fandom.com/wiki/Computer_Science_and_Engineering

**Comment by PKUFlyingPig** [comment]
> C/C++书籍建议直接指向stackoverflow： https://stackoverflow.com/questions/562303/the-definitive-c-book-guide-and-list https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list
> 
> 关于Python的书，个人认为https://pythonbooks.org/ 里面分类和简介挺不错的。
> 
> 此外，关于Computer Science的各个主题的教材，4chan Science Wiki里面挺全面的：https://4chan-science.fandom.com/wiki/Computer_Science_and_Engineering

感谢总结，已经汇入新的提交。
