### ISSUE TITLE
modify  README documentation

### ISSUE THREAD

**Issue by jackyliu16** [PKUFlyingPig/cs-self-learning#186]
**请求将前两段修正如下**
Fixed：严谨性，通顺性。
TODO：逻辑连贯性（等我有空了提交pr）

### 以下为内容

~~新冠肆虐，网课当道，CS 爆火，这一系列的事件都让自学计算机成为了一种潮流。~~

随着新冠疫情以及其他因素的综合影响，越来越多国内外的优秀大学，选择公开自己的课程教学视频以及实验内容。对于在信息化时代的 的我们而言，毫不夸张地说，只要有毅力和兴趣，我们能够通过这些公开的资源自学的成果完全不亚于你在国内任何一所大学受到的本科 CS 教育（当然，这里单指计算机专业领域，大学带给你的显然不止是专业知识）。

**Comment by PKUFlyingPig** [comment]
"随着新冠疫情以及其他因素的综合影响": 什么其它因素？
"对于在信息化时代的 的我们而言，毫不夸张地说": "而言" 和 "地说" 重复
“我们能够通过这些公开的资源自学的成果完全不亚于你在国内任何一所大学受到的本科 CS 教育”：太长了
No offence, 我觉得原话更通顺一些。

**Comment by showthesunli** [comment]
> emm，那你改下“全部开源”吧，我这堆其实只是为了改一下这个字段，并且使其逻辑简单的连贯起来（显然我玩砸了）

全部开源不代表接受全部pr。
你可以直接pr，接受与否是维护者的事情。
如果你觉得自己的pr真的非常有价值，而维护者又不接受你pr的话，你可以自己fork，自己维护的嘛

**Comment by jackyliu16** [comment]
啊这...我其实说的那个“全部开源”指的是README第二段的那个...不是说这个仓库
