### ISSUE TITLE
有文件系统，对象存储方面的课程吗

### ISSUE THREAD

**Issue by iamazy** [PKUFlyingPig/cs-self-learning#193]

**Comment by PKUFlyingPig** [comment]
操作系统里会涉及文件系统。对象存储不太明白具体是指？aws的 object store吗？

**Comment by iamazy** [comment]
> 操作系统里会涉及文件系统。对象存储不太明白具体是指？aws的 object store吗？

是的，如 S3，seaweedfs，cubefs 等等

**Comment by PKUFlyingPig** [comment]
看官方文档吧
