### ISSUE TITLE
CMU15-213,CMU15-445,CS61B,6.S081

### ISSUE THREAD

**Issue by ArdxWe** [PKUFlyingPig/cs-self-learning#20]
目前正在做CMU15-445-20fall和CS61B-18sp,有兴趣交流的朋友可以联系我，wechat 18845895492

**Comment by PKUFlyingPig** [comment]
请问这种方式有找到志同道合的自学朋友嘛，欢迎反馈意见以供参考。

**Comment by ArdxWe** [comment]
yes 我拉了56个人的群组在讨论 不过大家的课程可能不太相似，讨论的只能是广义的computer science 吧

flyingpig ***@***.***> 于2021年12月24日周五 22:10写道：
