### ISSUE TITLE
机器学习/深度学习自学的时候一本很有用的书

### ISSUE THREAD

**Issue by PKUxxz** [PKUFlyingPig/cs-self-learning#21]
书名叫Dive into Deep Learning, 也有中文版，翻译得还算不错，叫《动手学深度学习》
这书也有自己的官网，里头好像可以直接看/下载，并且书里面的代码也可以找到http://zh.d2l.ai/

**Comment by subfish-zhou** [comment]
这书唯一一个缺点是用的框架叫MXnet，一般没人用，不过有人用Pytorch重构过这本书 http://tangshusen.me/Dive-into-DL-PyTorch/#/

**Comment by IndifferentArea** [comment]
这本书的作者之一李沐老师在bilibili同步更新了和斯坦福一样的中文配套课程

**Comment by PKUFlyingPig** [comment]
已添加进“好书推荐模块”，感谢分享。
