### ISSUE TITLE
[ENHANCE] i18n supports?

### ISSUE THREAD

**Issue by BarbarossaWang** [PKUFlyingPig/cs-self-learning#216]
Why not integrate this repo and [PKUFlyingPig/Self-learning-Computer-Science](https://github.com/PKUFlyingPig/Self-learning-Computer-Science) into the same website?

**Comment by PKUFlyingPig** [comment]
[PKUFlyingPig/Self-learning-Computer-Science](https://github.com/PKUFlyingPig/Self-learning-Computer-Science) was simply a blog I rushed in two days. Currently, I do not have time to maintain two language versions. It's great if you want to contribute and extend csdiy.wiki into an English version.

**Comment by PKUFlyingPig** [comment]
This issue has been moved into this #222
