### ISSUE TITLE
关于课程名可能导致的误解问题

### ISSUE THREAD

**Issue by IndifferentArea** [PKUFlyingPig/cs-self-learning#218]
新增的cmu mlsys课程应该是名为CMU10-714：dlsys的课程，看名字应该是专注于深度学习系统

![image](https://user-images.githubusercontent.com/74698401/188827340-3d1b3a69-1d47-463c-bb49-3d39abf9193f.png)

（图片来源https://forum.dlsyscourse.org/login）

cmu目前机器学习系统的课程名为CMU15-849 https://www.cs.cmu.edu/~zhihaoj2/15-849/

**Comment by PKUFlyingPig** [comment]
感谢指出，方便的话可以提个 PR fix 一下 ～

**Comment by IndifferentArea** [comment]
ok
