### ISSUE TITLE
请问有没有推荐的java入门课程或者面向对象入门课程

### ISSUE THREAD

**Issue by william0620** [PKUFlyingPig/cs-self-learning#220]

**Comment by PKUFlyingPig** [comment]
MIT6.031

**Comment by william0620** [comment]
感谢回复，请问这课主要就是自己看website上的reading嘛，只看到有同学搬运的16年的视频，但似乎都是对reading做解释。

**Comment by PKUFlyingPig** [comment]
Reading 可以看 website 上最新版本的，编程作业 [2016 版本](https://ocw.mit.edu/courses/6-005-software-construction-spring-2016/pages/syllabus/) 的有开源（那时候这门课还叫 6.005）
