### ISSUE TITLE
"MIT18.06: Linear Algebra": "数学基础/MITLA.md"

### ISSUE THREAD

**Issue by PKUFlyingPig** [PKUFlyingPig/cs-self-learning#226]

**Comment by smxm** [comment]
"In addition to the course materials, the famous Youtuber 3Blue1Brown's video series [The Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) are also great learning resourses."
Is the spelling of resourses wrong, it should be resources?
