### ISSUE TITLE
[课程请求]优化算法？

### ISSUE THREAD

**Issue by HuengchI** [PKUFlyingPig/cs-self-learning#263]
朋友们，请问有没有具体讲优化算法的课，比如Convex Optimization、Non-Convex Optimization？

**Comment by PKUFlyingPig** [comment]
https://csdiy.wiki/%E6%95%B0%E5%AD%A6%E8%BF%9B%E9%98%B6/convex/

**Comment by HuengchI** [comment]
谢谢，怪我看得不仔细 @PKUFlyingPig
