### ISSUE TITLE
希望可以在“必学工具”下添加学习workflow的搭建

### ISSUE THREAD

**Issue by HardwayLinka** [PKUFlyingPig/cs-self-learning#275]
您好~ 您的这个开源项目应该能让还在校的同学受益无穷，虽然我已经工作了，但我也会想 “要是我在大学能看到这样的宝藏就好了”。
为了能为此项目出一份力，我想能不能麻烦您在该项目的 “必学工具” 栏目下添加 ”学习工作流的搭建“。因为学习的过程需要对信息进行管理、处理以及回顾，所以打造出自己一个比较稳定的学习的工作流其实是挺重要的。为了让在校的学生能够有意识形成自己的学习工作流，我可以提供我写的相关的  [文章](https://sspai.com/post/76113)，倘若您有更好的见解也麻烦您进行补充~ 
希望能得到您的答复~

**Comment by PKUFlyingPig** [comment]
您可以直接 fork 之后修改然后提交 PR 的。

**Comment by PKUFlyingPig** [comment]
#278
