### ISSUE TITLE
[ENHANCE]对于增加课程的建议

### ISSUE THREAD

**Issue by kroulis** [PKUFlyingPig/cs-self-learning#277]
希望能将
UC Berkeley的[CS 168](https://cs168.io/)
 Introduction to the Internet: Architecture and Protocols 加入到【计算机网络】课程目录中。
希望能将
UC Berkeley的[CS 164](https://inst.eecs.berkeley.edu/~cs164/fa20/) Programming Languages and Compilers 加入到【编译原理】课程目录中。
希望能将
UC Berkeley的[CS184](https://cs184.eecs.berkeley.edu/sp22) Computer Graphics and Imaging 加入到【计算机图形学】课程目录中。

**Comment by PKUFlyingPig** [comment]
CS164 在 TODO List 里，不过另外两门课我没有了解过，不清楚内容质量具体如何，你上过的话可以提 PR。
