### ISSUE TITLE
[RFC] 扩充环境配置对应的章节

### ISSUE THREAD

**Issue by NoDocCat** [PKUFlyingPig/cs-self-learning#292]
大部分用到的环境, 在各平台都能用包管理工具搞定. 感觉加上这方面的内容应该能减少初学者浪费在环境搭建上的时间.

- [brew](https://brew.sh/) - macOS
- [scoop](https://scoop.sh/) - windows

有能力用上 Linux 的同学应该不需要这种教程吧🤣

**Comment by PKUFlyingPig** [comment]
书中已经有了对应的 section： https://csdiy.wiki/CS%E5%AD%A6%E4%B9%A0%E8%A7%84%E5%88%92/#pc

**Comment by NoDocCat** [comment]
这段我看到了, 但是感觉太简陋了, 引用的那份在 window 下搭建环境的 repo 也有点过时了.
现在 windows 下完全可以做的和 macOS 下差不多的体验. 比如安装 gcc 和 python, 只需要:

```shell
scoop install gcc
scoop install python
```

**Comment by NoDocCat** [comment]
@PKUFlyingPig 本来打算周六日写的, 然后沉迷 TI 无法自拔 😂

这两天我把这两章写一下, 写完提 PR
