### ISSUE TITLE
申请加入贡献者

### ISSUE THREAD

**Issue by taylover2016** [PKUFlyingPig/cs-self-learning#31]
哈啰， 同学你好~

刚刚在公众号“夕小瑶的卖萌屋”看到了关于这样一份“CS自学指南”的推荐，看完之后感慨很深，也想起了漫长的自我学习之路。

同时对于部分内容感觉自己能尽一份绵薄之力予以贡献完善，所以想申请加入贡献者的行列。
有关动机与详情我已经按照指南主页发到了同学的pku邮箱里了，希望能获得同学你的同意~

不论结果如何，我都会持续关注你的项目哦~ 加油~

**Comment by ysj1173886760** [comment]
你好，我也是和你一样希望参与贡献的爱好者。你可以fork以后直接提交pull request，具体的格式可以看这个
![image](https://user-images.githubusercontent.com/42030331/147047665-19d89b19-4feb-4915-8fee-3e188a37191c.png)
