### ISSUE TITLE
link to z-library is dead

### ISSUE THREAD

**Issue by WJWsir** [PKUFlyingPig/cs-self-learning#316]
### z-library链接失效

问题描述：由于美国对z-library网站服务器多个使用的域名封杀导致现文档对其的链接失效

**Comment by PKUFlyingPig** [comment]
你们可以 file 一个 PR 修复这个挂掉的链接

**Comment by svenust** [comment]
what's a PR?

**Comment by PKUFlyingPig** [comment]
Pull Request

**Comment by ArtieLiu** [comment]
Raised [PR](https://github.com/PKUFlyingPig/cs-self-learning/pull/334) to update z-lib link to the following:

> 新网站：[z-lib.is](https://z-lib.is)

thanks, @xiaotianxt

**Comment by LingkKang** [comment]
@ArtieLiu I'm not sure why your PR did not working, and I made a new one, with it's Tor location added.

@xiaotianxt Thanks a lot.

**Comment by ArtieLiu** [comment]
hi @LingkKang, sorry for the closed pr, later I made [another one](https://github.com/PKUFlyingPig/cs-self-learning/pull/341/) to fix the broken link which updated to [z-lib.is](https://z-lib.is/). Maybe that link was baned for a few days just after that pr was merged.

**Comment by LingkKang** [comment]
@ArtieLiu Alright.

@PKUFlyingPig Maybe you can close this issue now.
