### ISSUE TITLE
申请北大临时邮箱

### ISSUE THREAD

**Issue by zmz125** [PKUFlyingPig/cs-self-learning#33]
请问非本校的学生能否申请北大临时邮箱？
北大周边学校的学生能去听北大的公开课吗？或者说能申请其他什么资源呢？

**Comment by PKUFlyingPig** [comment]
临时邮箱的话据我所知是没有的。旁听的话因为现在疫情防控的原因可能有些困难，之前是可以预约进校的。课程资源有些国内的在线课程平台（例如华文慕课，智慧树）是有北大的公开课的。

**Comment by zmz125** [comment]
好的感谢博主
