### ISSUE TITLE
建议加一章:信息检索

### ISSUE THREAD

**Issue by wuqi** [PKUFlyingPig/cs-self-learning#337]
信息检索就是如何高效利用搜索引擎,我是个面向google编程的废柴老手,毕竟google甚至会用百度就能解决大部分问题,主要是告诉下小白咋用高级搜索,哪怕百度,用上几个关键字/时间/site 基本就能检索到有用信息
 
建议直接加上 [提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

**Comment by PKUFlyingPig** [comment]
提问的智慧书中已经提到了，在“一个仅供参考的学习规划”那一章。关于高效检索的内容我觉得确实很有帮助，欢迎提交 PR。

**Comment by PKUFlyingPig** [comment]
能 file 一个 PR 吗，我看了一下感觉还不错。

**Comment by ratio-dd** [comment]
感觉挺好的兄弟，上大学这几年我感觉最有用的课就是信息检索了

**Comment by PKUFlyingPig** [comment]
#348
