### ISSUE TITLE
关于CS126的课程资料问题

### ISSUE THREAD

**Issue by lenglingxuan** [PKUFlyingPig/cs-self-learning#354]
想请问一下作者CS126的习题答案是在哪里找的？我进入课程官网能看到homework和solution，但是只有homework能打开，solution进不去。

**Comment by PKUFlyingPig** [comment]
在课程进行中的时候会有 solution 公布，但在课程结束后会被统一移除。我是当时在课程同步开设的过程中下载下来的。

**Comment by leng-lingxuan** [comment]
> 在课程进行中的时候会有 solution 公布，但在课程结束后会被统一移除。我是当时在课程同步开设的过程中下载下来的。

好的，谢谢
