### ISSUE TITLE
关于函数式编程内容

### ISSUE THREAD

**Issue by fecet** [PKUFlyingPig/cs-self-learning#356]
是否有计划添加相关内容

**Comment by showthesunli** [comment]
我正在学一门函数式编程的课[haskell mooc](https://haskell.mooc.fi/)

赫尔辛基大学的免费公开课，目前还剩最后三章没学完。
本来打算完全学完之后，向这个项目pr一下。

现在看见你这个issue之后，就先向你推荐一下吧。这门课很不错，特别是练习。这么说吧，我前段时间刚刷完cs61a，我感觉这门课练习的设计不亚于cs61a。

**Comment by fecet** [comment]
> 我正在学一门函数式编程的课[haskell mooc](https://haskell.mooc.fi/)
> 
> 赫尔辛基大学的免费公开课，目前还剩最后三章没学完。 本来打算完全学完之后，向这个项目pr一下。
> 
> 现在看见你这个issue之后，就先向你推荐一下吧。这门课很不错，特别是练习。这么说吧，我前段时间刚刷完cs61a，我感觉这门课练习的设计不亚于cs61a。

大概看了一下, 很精彩的课程, 期待PR

**Comment by PKUFlyingPig** [comment]
书中提到的 OCaml 的课程 https://cs3110.github.io/textbook/cover.html
