### ISSUE TITLE
求解-我未撰写评论却屡屡收到Reply邮件

### ISSUE THREAD

**Issue by WYYlost** [PKUFlyingPig/cs-self-learning#365]
### 如题
**请问如何关闭，现在reply都是些🪜的，好像没什么用**

**Comment by PKUFlyingPig** [comment]
您可以在右上角的 watch 设置里把 discussion 取消勾选。
先点击 watch 按钮右侧的小三角
![image](https://user-images.githubusercontent.com/60659728/209066202-f011745e-d476-46e6-9913-c9eae3d5d7bb.png)
选择 custom 并勾选想要获得通知的内容
![image](https://user-images.githubusercontent.com/60659728/209066332-cf1d6ecd-c552-4453-834a-c262df405b82.png)

**Comment by WYYlost** [comment]
> 您可以在右上角的手表设置里把讨论取消勾选。 先点击手表按右上角的小三角 选择自定义并勾选想要获得通晓的内容 ![图片](https://user-images.githubusercontent.com/60659728/209066202-f011745e-d476-46e6-9913-c9eae3d5d7bb.png) ![图片](https://user-images.githubusercontent.com/60659728/209066332-cf1d6ecd-c552-4453-834a-c262df405b82.png)

**大佬我这里一开始就没有勾选**
<img width="298" alt="image" src="https://user-images.githubusercontent.com/26041724/209068669-36d4a8d1-ddd4-48c6-9de5-23cc5dd2152e.png">

**Comment by PKUFlyingPig** [comment]
请问解决了吗？

**Comment by WYYlost** [comment]
目前解决了，谢谢大佬
