### ISSUE TITLE
希望网站点开链接默认是在新标签页打开而不是跳转

### ISSUE THREAD

**Issue by Ninzeige** [PKUFlyingPig/cs-self-learning#37]

**Comment by Ninzeige** [comment]
非常感谢作者的资源！但是有时候想要来回浏览资源，习惯性点了链接就跳转了还得重新退回来，总不能一直按着ctrl键浏览网页吧😂如果可以改进这一点会更舒服

**Comment by ysj1173886760** [comment]
这个应该是个人喜好，因人而异吧

**Comment by PKUFlyingPig** [comment]
印象里是可以设置浏览器默认用新标签页打开链接的。一般触摸屏用户还是比较习惯回退这种方式。

**Comment by xuke-hat** [comment]
你可以点击鼠标滚轮来打开新标签页

**Comment by Wang275** [comment]
> 你可以点击鼠标滚轮来打开新标签页

第一次知道原来鼠标滚轮还有这功能
