### ISSUE TITLE
关于计算机自学的分支整理的request

### ISSUE THREAD

**Issue by BAIYIMING520** [PKUFlyingPig/cs-self-learning#42]
为wiki中整理展示国外一流的课程教育资源
实际生活中 除了这些基础进阶课程 还不足以让一个cs的学生纵向延伸 成为一个方向的专家 
是否可以考虑在不同分支下引入经典论文呢？
例如以dataBase为例子
可以有如下的几个方向 
1. 关于优化器优化的方向的研究
比如sigmod上有一些经典论文 例如在rbo的部分 有微软Orthogonal-Optimization-of-Subqueries-and-Aggregation 这种经典论文
CBO甚至有老的IBM的关于system-r Access Path Selection in a Relational Database Management System 这种经典论文
甚至是一个逻辑优化规则的推导
2.比如现在在分布式条件下 数据库的计算/存储
比如google经典三大论文 mapreduce  big-table GFS三篇论文
....
是否可以考虑号召生成各个分支 来让大家把各个分支下的必修课程和论文做一个list

**Comment by PKUFlyingPig** [comment]
不错的建议，但分支按照什么方式来分类呢？另外这些深入学习知识的总结可能得在读phd的在一个方向研究一到两年后才能确保质量，而且难免带有强烈的个人bias。或许可以更细化一下受众的需求从而确定list的内容。

**Comment by BAIYIMING520** [comment]
vx&nbsp;
CauchyBai



------------------ 原始邮件 ------------------
发件人: flyingpig ***@***.***&gt;
发送时间: 2022年1月12日 18:16
收件人: PKUFlyingPig/cs-self-learning ***@***.***&gt;
抄送: CauthyBai ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PKUFlyingPig/cs-self-learning] 关于计算机自学的分支整理的request (Issue #42)





 
不错的建议，但分支按照什么方式来分类呢？另外这些深入学习知识的总结可能得在读phd的在一个方向研究一到两年后才能确保质量，而且难免带有强烈的个人bias。或许可以更细化一下受众的需求从而确定list的内容。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fitiger** [comment]
个人觉得对于“专家”而言不应该有既定的路线，但是对于职业道路的选择却可以有清晰的规划。
比如对于的职位面试需要掌握哪些技能，实际工作又需要哪些技能。

- DevOps Engineer
- Backend dev
- Frontend dev
- Administrator
- Data Scientist
- Data Engineer

除了这些课程很多时候我们会希望有一些有趣的project可以学以致用，加深理解，也可以收集一些优秀的 example project和上手比较容易的开源项目。

**Comment by IndifferentArea** [comment]
目的不同，路线不同，我觉得没法整合。
