### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by dazhuang201915302** [PKUFlyingPig/cs-self-learning#424]
非常感谢~~~~

**Comment by PKUFlyingPig** [comment]
很高兴这个 repo 对你有所帮助，也欢迎你把它推荐给更多的人。但 issues 是供大家发布自学交流群、推荐优质课程以及指出书中错误的地方，所以我将关闭你的这个 issue。

**Comment by dazhuang201915302** [comment]
不好意思，刚入手github操作不是很熟练，只是看到文章后想评论一下表示对你的感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月18日(周六) 晚上8:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PKUFlyingPig/cs-self-learning] 非常感谢 (Issue #424)




 
很高兴这个 repo 对你有所帮助，也欢迎你把它推荐给更多的人。但 issues 是供大家发布自学交流群、推荐优质课程以及指出书中错误的地方，所以我将关闭你的这个 issue。
