### ISSUE TITLE
[SUGGESTION] 是否应该将常用的计算机相关问答网站，百科以及论坛添加入实用工具箱

### ISSUE THREAD

**Issue by ulic-youthlic** [PKUFlyingPig/cs-self-learning#455]
讨论一下，有无必要将 stakeoverflow、github issue（这看起来有点蠢，但是确实有人把github当作一个“白嫖网站”，从不留意问答）、reddit 的一些相关贴，甚至 ubuntu 论坛、arch wiki 以及论坛添加到 `实用工具箱` 里，并以单独的小标题列出。

**Comment by PKUFlyingPig** [comment]
不错的建议，可以集思广益提交一个 PR

**Comment by ulic-youthlic** [comment]
是否应该加入CSDN此类广告较多，但是新手容易接触的网站。
实际上，根据个人见解，使用此类网站的时候，基本是因为google搜出来了。但我从未主动去上面找东西。
