### ISSUE TITLE
能贡献国内的课程么

### ISSUE THREAD

**Issue by NaChen95** [PKUFlyingPig/cs-self-learning#460]
能贡献哈工大[李治军老师的操作系统课程](https://www.bilibili.com/video/BV19r4y1b7Aw/?p=1&vd_source=683a01bdc1972c35f5b27445f6fa8ccd)么，讲的也很好，注重代码和实验，适合英文欠佳的同学学习

**Comment by PKUFlyingPig** [comment]
可以提交一个 PR 看看
