### ISSUE TITLE
最近在自学计算机网络，有群吗，求拉

### ISSUE THREAD

**Issue by iamazy** [PKUFlyingPig/cs-self-learning#466]

**Comment by aaashuow** [comment]
同样开始学计网，准备八月前能刷完cs144，一起吗？

**Comment by iamazy** [comment]
怎么联系你呢

**Comment by iamazy** [comment]
> 同样开始学计网，准备八月前能刷完cs144，一起吗？

怎么联系你呢

**Comment by hhh2210** [comment]
> > 同样开始学计网，准备八月前能刷完cs144，一起吗？
> 
> 怎么联系你呢

能否也联系下俺？tg：https://t.me/Larry2210
