### ISSUE TITLE
英文看不懂怎么办啊

### ISSUE THREAD

**Issue by moonwhitee** [PKUFlyingPig/cs-self-learning#47]
英文看不懂怎么办啊

**Comment by SuperBILLY65535** [comment]
实在不行就词典软件或者google translate, 但是这样会显著降低效率
养成英文阅读的习惯还是很有必要的（

**Comment by PKUFlyingPig** [comment]
可以具体到哪一门课的哪些内容吗？例如是课程视频、课程作业还是教材？课程视频的话有些课程b站是有人工字幕的，教材和作业可以用谷歌翻译。其实这些课涉及的英文除了一些专有名词的话都还是相对基础的，实在困难的话也只有多看多练了。

**Comment by moonwhitee** [comment]
谢谢大佬们，主要是有一些文档也是英文的，比如qt，或者github上一些其他的项目

**Comment by PKUFlyingPig** [comment]
官方文档一般都有中文版，可以自行搜索。github项目这就没办法了，外国人的项目毕竟还是英文居多。

**Comment by moonwhitee** [comment]
谢谢大佬，新年快乐！
