### ISSUE TITLE
有人文社科专业的想要一起学习么

### ISSUE THREAD

**Issue by nathanchen1126** [PKUFlyingPig/cs-self-learning#496]
如题

**Comment by RedBird233** [comment]
有的，有的...不知题主怎么和您联系。。。咱也想找个学习搭子😥

**Comment by Lena199928** [comment]
同问，怎么联系

**Comment by nathanchen1126** [comment]
居然有人回复了诶！可以加我微信，就是邮箱号的前面这个手机号，我们可以拉个群



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月04日 14:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) |

有的，有的...不知题主怎么和您联系。。。咱也想找个学习搭子😥

**Comment by nathanchen1126** [comment]
居然有人回复！可以加我微信，就是邮箱号前面这个手机号！我们可以拉个群



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月05日 12:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) |

同问，怎么联系

**Comment by Lena199928** [comment]
> 居然有人回复！可以加我微信，就是邮箱号前面这个手机号！我们可以拉个群
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月05日 12:33 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) | 同问，怎么联系 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

题主，没有看到邮箱前面有数字

**Comment by nathanchen1126** [comment]
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月05日 13:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) |

居然有人回复！可以加我微信，就是邮箱号前面这个手机号！我们可以拉个群
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年09月05日 12:33 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) | 同问，怎么联系 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

题主，没有看到邮箱前面有数字

**Comment by nathanchen1126** [comment]
啊啊，是18018394950



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月05日 13:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) |

居然有人回复！可以加我微信，就是邮箱号前面这个手机号！我们可以拉个群
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年09月05日 12:33 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [PKUFlyingPig/cs-self-learning] 有人文社科专业的想要一起学习么 (Issue #496) | 同问，怎么联系 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

题主，没有看到邮箱前面有数字

**Comment by Lena199928** [comment]
> 啊啊，是[18018394950](tel:18018394950)
> […](#)

好滴已经发送申请了

**Comment by nathanchen1126** [comment]
可以搜索我的手机号，18018394950，添加微信，我想能不能我们拉个群这样
















在 2023-09-04 14:32:57，"RedBird233" ***@***.***> 写道：

有的，有的...不知题主怎么和您联系。。。咱也想找个学习搭子

**Comment by PKUFlyingPig** [comment]
建议不要公开手机号这类隐私信息，可以邮箱私下交流联系方式

**Comment by nathanchen1126** [comment]
> 建议不要公开手机号这类隐私信息，可以邮箱私下交流联系方式

感谢，已邮件联系

**Comment by nathanchen1126** [comment]
可以在此处回复邮箱，题主会联系各位~

**Comment by k1ikl** [comment]
K1ikl@outlook.com
