### ISSUE TITLE
你好作者，想问问您CS61C 20SUMMER的是自己写测试吗？gradescope我没有课程代码，或者您有课程代码吗

### ISSUE THREAD

**Issue by Amo-zwk** [PKUFlyingPig/cs-self-learning#50]
你好作者，想问问您CS61C 20SUMMER的是自己写测试吗？gradescope我没有课程代码，或者您有课程代码吗

**Comment by PKUFlyingPig** [comment]
课程网站提供了课程代码，里面附有测试，请先仔细阅读它的lab，project描述。我的课程代码在这里 https://github.com/PKUFlyingPig/CS61C-summer20

**Comment by Amo-zwk** [comment]
好的 ， thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PKUFlyingPig/cs-self-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月12日(星期六) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PKUFlyingPig/cs-self-learning] 你好作者，想问问您CS61C 20SUMMER的是自己写测试吗？gradescope我没有课程代码，或者您有课程代码吗 (Issue #50)





 
课程网站提供了课程代码，里面附有测试，请先仔细阅读它的lab，project描述。我的课程代码在这里 https://github.com/PKUFlyingPig/CS61C-summer20
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
