### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by bytearchive** [PKUFlyingPig/cs-self-learning#500]
Can someone create an english translation for this?

**Comment by PKUFlyingPig** [comment]
over 70% of the materials have been translated, see #222

**Comment by PKUFlyingPig** [comment]
You can change the language in the upper bar on the website:
<img width="399" alt="image" src="https://github.com/PKUFlyingPig/cs-self-learning/assets/60659728/bc1470aa-0afc-465c-a07c-ef9121b53e4b">
