### ISSUE TITLE
[课程分类建议] 程序语言设计 -> 程序语言设计与分析

### ISSUE THREAD

**Issue by Qi-Zhan** [PKUFlyingPig/cs-self-learning#521]
建议 程序语言设计 这一分类改名为  程序语言设计与分析，或者 编程语言设计与分析，把 NJU, PKU 的软件分析课程并入这个范畴。
我认为软件分析和 PL 相关性更高，适合放在一起。而编译原理本身就是一门比较独立的课程，单独一类即可

**Comment by PKUFlyingPig** [comment]
感觉很合理，方便的话可以提交一个 PR 进行修改

**Comment by Qi-Zhan** [comment]
好的
