### ISSUE TITLE
求推荐算法基础课程

### ISSUE THREAD

**Issue by rmd1710714107** [PKUFlyingPig/cs-self-learning#563]
有没有适合算法小白的课程啊，基础一点的。看了coursea的算法课程，上来就是并查集给我整懵了都。

**Comment by PKUFlyingPig** [comment]
https://csdiy.wiki/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/CS61B/

**Comment by wizardforcel** [comment]
<https://www.hello-algo.com/>
