### ISSUE TITLE
关于x86汇编语言的推荐

### ISSUE THREAD

**Issue by Zanghu-ze** [PKUFlyingPig/cs-self-learning#63]
你好，在按照您网站学习路线的视频之后，我发现其中缺少对x86汇编语言课程的推荐，所以希望请教对于汇编应该如何学习才可以进入到后续OS和体系结构的学习？

**Comment by ysj1173886760** [comment]
你好，在CSAPP这本书的第三章有设计到x86的汇编，可以看一下。对应的课是cmu15-213
在CS61C中则有涉及到riscv的汇编。
