### ISSUE TITLE
在课程简介页面中，课程资源链接点击后会在本窗口跳转，希望改为新开标签页

### ISSUE THREAD

**Issue by InsideEmpire** [PKUFlyingPig/cs-self-learning#678]
在课程简介页面中，点击课程资源的链接时，页面会直接在本窗口跳转，而不是在新标签页中打开。这样每次点击链接后，用户需要手动返回，影响了浏览体验。如果链接能够默认在新标签页中打开，会更加方便。

希望在课程简介页面的课程资源链接点击后，能够在新标签页中打开。

	1.	进入任意课程的简介页面
	2.	点击页面中的课程资源链接
	3.	当前页面跳转到链接地址，而非新标签页打开

希望在 HTML 的` <a> `标签中添加` target="_blank" `属性，这样点击链接后会在新标签页中打开。

**Comment by PKUFlyingPig** [comment]
浏览器应该可以设置默认总是在新标签页中打开？

**Comment by InsideEmpire** [comment]
> 浏览器应该可以设置默认总是在新标签页中打开？

是可以这样，但选择课程标签的时候也会开太多不必要的新标签页，问题就是markdown文件超链接的默认跳转模式是页内跳转。

**Comment by PKUFlyingPig** [comment]
把整个仓库的 markdown 格式下的超链接都修改一遍工作量有点大，而且对之后的 contributor 是个额外的负担。是否有某种解决方案可以进行全局设置而不需要对每个 markdown 进行修改呢？

**Comment by InsideEmpire** [comment]
> 把整个仓库的 markdown 格式下的超链接都修改一遍工作量有点大，而且对之后的 contributor 是个额外的负担。是否有某种解决方案可以进行全局设置而不需要对每个 markdown 进行修改呢？

先留着issue在考虑一下吧

**Comment by Bioboy-Learning** [comment]
摁鼠标中键就是在新标签页打开了

**Comment by InsideEmpire** [comment]
> 摁鼠标中键就是在新标签页打开了

这样确实可以，但多少有些反直觉。既然本站是通过mkdocs搭建的，我查询到mkdocs- external-links插件可以做到将markdown文件内的所有外部链接定义为在新建标签页中打开

**Comment by PKUFlyingPig** [comment]
> > 摁鼠标中键就是在新标签页打开了
> 
> 这样确实可以，但多少有些反直觉。既然本站是通过mkdocs搭建的，我查询到mkdocs- external-links插件可以做到将markdown文件内的所有外部链接定义为在新建标签页中打开

您有空的话可以在本地调试研究下，确定可行的话提交一个 PR
